### ISSUE TITLE
Change station by selecting new station

### ISSUE THREAD

**Issue by jeffmcneill** [cheshire137/soma-chrome#18]
Currently one has to Pause, then select from dropdown, then Play.

Faster would be simply changing the station (not having it unselectable while playing).

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/13011201/aa8b8306-d173-11e5-90fe-4f9052fb13eb.png)

**Comment by cheshire137** [comment]
Haha that is the most roundabout way of giving a :+1: +1. ;) I'll work on this next!

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/13021795/0679396a-d1ab-11e5-98c9-06bb50359c44.png)

**Comment by cheshire137** [comment]
This is fixed in https://github.com/cheshire137/soma-chrome/commit/3d7a47bbd5029b759f2a00fbb6fdf0181e90447c but not yet pushed to the Chrome Store.

**Comment by cheshire137** [comment]
Version 0.0.0.9 is now live in the Chrome Store!

**Comment by corysimmons** [comment]
![image](https://cloud.githubusercontent.com/assets/224636/13031751/0d5e92e8-d2a5-11e5-819e-354542bf3956.png)

**Comment by cheshire137** [comment]
How deep can this rabbit hole go...?
