### ISSUE TITLE
Current track info not showing

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/soma-chrome#39]
From feedback in the Chrome Web Store:

> it doesn't scrobble to Last.FM.

> Hey guys. Please help me with scrobbling.

> I disconnected and re-authenticated Last.fm multiple times and it still doesn't scrobble. Not sure what I'm doing wrong. Also, notifications aren't showing up either.

> Extension doesn't scrobble.

> just started using this. won't scrobble.

> Having trouble getting it to scrobble though.

**Comment by cheshire137** [comment]
I got an SSL error trying to get the current track from https://api.somascrobbler.com/api/v1/nowplaying/suburbsofgoa. https://somascrobbler.com/ is still up but the API it links to, http://api.somascrobbler.com/, also doesn't load.

**Comment by rustyhodge** [comment]
Just for the record, SomaFM would prefer you don’t scrobble this. Last.FM is owned by CBS who uses that data for their own streaming. Not to mention CBS has been really harmful to indie broadcasters like SomaFM. We have had to send them cease and desists in the past for cloning our channels *and* using our names. Really uncool of them.

**Comment by cheshire137** [comment]
> We have had to send them cease and desists in the past for cloning our channels *and* using our names.

That is really shitty. 😞 

The thing stopping scrobbling from working seems to be the extension not knowing what song is currently being played. Even if scrobbling support is not restored, it would be ideal to see the current song or at least recently played songs on the active station. If the SomaScrobbler API remains down, I could do in this extension what I do in my standalone Electron app, which is pull the list of recent songs from api.somafm.com:

https://github.com/cheshire137/huxleyfm/blob/c038541b913948888f582bf803b1a5fcdd2f724d/models/soma.js#L26-L30

**Comment by cheshire137** [comment]
Just to note, I think it would be especially crappy to switch to using SomaFM's own API to get data and then use that data in a way SomaFM explicitly doesn't like. I think what I'll end up doing is dropping the dependency on the SomaScrobbler API and making this extension like [HuxleyFM](https://github.com/cheshire137/huxleyfm) in that it a) doesn't scrobble to Last.fm, b) gets its track data from the SomaFM API, and c) shows a list of the recent tracks from a station instead of showing one track that's currently playing.

**Comment by code-for-coffee** [comment]
Just chiming in to add that I also think it is awful how LastFM/CBS has affected SomaFM and I think it is a good decision to support @rustyhodge and SomaFM based on your decision to remove scrobbling. The LastFM API has been on life support for a while anyways, right?

**Comment by cheshire137** [comment]
> The LastFM API has been on life support for a while

That's been my impression when I've gone to the Last.fm API page the last few times, yeah. I remember there was some trouble getting API keys I'd generated in the past.

**Comment by rustyhodge** [comment]
Would it simplify things if I could give you a JSON or XML file that has only the currently playing song (and possible the time it started playing at)?

**Comment by cheshire137** [comment]
Thank you for the offer! Getting the recent tracks list per station is pretty easy using the endpoint that already exists, and it already includes a timestamp:

```json
{
	"id": "poptron",
	"songs":[
		{
			"title": "Frequent Flyer",
			"artist": "Chromeo",
			"album": "White Women",
			"albumart": "",
			"date": "1517442748"
		},
```

-- http://api.somafm.com/songs/poptron.json

I could see the duration of each track, if that's known, being added to this endpoint ☝️. From the duration + the timestamp, I could determine if a track is still playing or not.

If durations for tracks aren't known, then an endpoint that has just the current song in a station would be useful, or if the track with the most recent `date` in the existing /songs/[channel].json endpoint is definitely the currently playing track, then I could use that knowledge.

What could be interesting, and maybe this is the format you were thinking instead of a separate endpoint per station, would be a single endpoint with a list of all the stations and the active song on each. Then in the extension, in addition to the station name, I could also list the song that's playing. That could help a user choose which station they want to listen to, especially if they recognize the song/artist being played.

It's up to you! I think the extension would be just fine using existing SomaFM API endpoints. 👌

**Comment by m-ad** [comment]
I understand the problems with Last.fm. How about Libre.fm? It is a free software alternative to Last.fm. It might be worth considering to just switch services instead of dropping scrobbling support altogether. Just an idea.
